### ISSUE TITLE
Improves

### ISSUE THREAD

**Issue by Julia-1994** [Michael18811380328/HelloBlog#1]

**Comment by Julia-1994** [comment]
站点问题：
1、SQL 部分文件路径大小写不正确，点击界面是404，下一个版本应该修复一下
2、每个页面可以加入百度统计，这个对性能影响不大
3、在每一个界面中增加 meta 标签，便于搜索引擎爬取
4、在搜索网站中，增加自己网站的域名
5、自己的首页增加其他大型网站的链接，有助于搜索引擎反向爬取
6、有没有必要把当前所有的日志和笔记从其他平台，搬运到 github page 平台？如果搬运，时间成本多少？
7、未来有没有必要自己搭建网站（不使用 github 平台，避免墙404）
8、不同站点维护的文档不同，以哪个站点为准？不可能同时维护多个相同的文档

思考：
1、数据库不同表之间的主键外键的关联，这个具体怎么使用，高级的查询语句需要处理哪些事情？
2、SQL语句中能否使用已有算法优化（二分搜索，快速排序）；数据库表的搜索能否使用树结构优化处理，而不是线性搜索
3、MYSQL 性能问题：如果并行请求很多，mysql 锁无法合理分配资源，产生延时。解决方法：使用 mamcache 作为中间层。

**Comment by Julia-1994** [comment]
- 当前 1.0 版本代码量接近 100MB，即将超出限制，未来可以将未编译部分和编译部分分别放在不同的 repo 中
- 删除部分没用的博客，从内容上减少代码量
- 网易云音乐插件装在根目录，不要装在每个界面上；百度统计插件需要到每一个页面上，可以统计不同界面的访问量。
- 整理一下 dev 分支 和 dev2 分支，简单维护

**Comment by Julia-1994** [comment]
根目录下面脚本可以单独放在一个 scripts 中，便于管理

**Comment by Julia-1994** [comment]
## todo

- 增加界面统计（https://starchart.cc/caarlos0/starcharts)
- 当前 1.0 版本代码量接近 100MB，即将超出限制，未来可以将未编译部分和编译部分分别放在不同的 repo 中
- 使用 lighthouse 优化界面 （todo）
- 编译成功后，上线后，在各大搜索引擎上面增加网站收录等（详见：https://blog.csdn.net/yuyuking/article/details/89374794）
- [x] 首页增加小游戏入口，然后点击进入小游戏列表，分别指向不同的小游戏
- [x] 整理一下 dev 分支 和 dev2 分支，简单维护
- [ ] 删除部分没用的博客，从内容上减少代码量
- [ ] 百度统计插件，应该写在每个界面上
- [ ] 网易云音乐插件装在根目录（或者直接使用 mp3 背景音乐）
- [ ] 小游戏最好支持 PC 端和 移动端分离；不同游戏适应于不同的场合
- [ ] 主页对应几个部分：前端（HelloWorld/HelloTs/HelloJS）；后端 (HelloPython/nodejs) ；算法(HelloLeetcode/interview)；小游戏(game)；个人感悟(Personal) 全部的文档在不同的子项目中，然后把基本成型的单独新建一个仓库（MichaelSite），定期把上面五个仓库的文档同步到这个仓库中；然后这个仓库只负责把渲染的部分展出出来（Views）。如果界面需要更改，那么从界面反馈到不同的子项目中，这样可以实现不同功能的分离。

- [ ] 全部操作使用脚本实现
- [ ] 增加一个脚本说明文档
- 不同的子项目内容分类优化
- 不同平台互相引流
- 不同子项目设置不同的样式
- 相关文档整理说明

**Comment by Michael18811380328** [comment]
可以在 helloSite 中维护 index.html 然后进行版本更新。编辑后，直接运行迁移脚本，将这个文件复制一份到 展示目录下，就不需要手动更改另一个项目的版本号了。

**Comment by Michael18811380328** [comment]
现在阅读文档，增加序号（00x），这样无法记录阅读的时间。未来可以考虑增加时间戳（2021-01-01-title）这样就可以对文档根据修改的时间直接排序了

**Comment by Michael18811380328** [comment]
博客的背景图显示是爬虫爬取的第三方的图片，未来可以考虑上传自己的图片（到另一个展示的代码仓库中）

**Comment by Michael18811380328** [comment]
二叉树的层序遍历：
https://michael18811380328.github.io/leetcode/site/algre/05-%E4%BA%8C%E5%8F%89%E6%A0%91%E5%B1%82%E5%BA%8F%E9%81%8D%E5%8E%86/
1、基本二叉树的层序遍历：使用BFS遍历，设置临时队列，每次循环临时队列，放置每一层的元素。
2、二叉树的锯齿层序遍历：遍历一层后，如果是奇数或者偶数，然后把结果数组 reverse 一下
3、二叉图的左视图右视图：BFS遍历每一层，获取每一层的第一个节点的 value 即可（使用DFS比较复杂）

**Comment by Michael18811380328** [comment]
第三方库现在有一个简单的介绍。可以对于常用的库，单独写一个文件夹，并加入一些例子和说明，这样使用比较方便。

展示的库中，主页面是一个 SPA，未来可以使用 react + webpack 构建一下。现在还是固定的 HTML。
